p2e-dev-node1 run script

diff --git a/local-bin/install b/local-bin/install
--- a/local-bin/install
+++ b/local-bin/install
@@ -5,12 +5,15 @@ echo "Installing to $localbin"
 
 mkdir -p ~/.local/bin/
 
-prog="p2e-dev-node1"
-if [ -r "${localbin}/${prog}" ]
-then
-	echo "${prog} - already installed "
-else
-	echo "${prog}- installing"
-	ln -s "${PWD}/${prog}" 	"${localbin}/" || echo "Failed to link"
-fi
+for prog in "p2e-dev-node1" "git-module-rm-all"
+do
 
+	if [ -r "${localbin}/${prog}" ]
+	then
+		echo "${prog} - already installed "
+	else
+		echo "${prog}- installing"
+		ln -s "${PWD}/${prog}" 	"${localbin}/" || echo "Failed to link"
+	fi
+
+done
