p2e and local-bin lua: refactor: auto fix indents tabs
simply the following code was run:
for fff in *  ; do  sed 's/[[:space:]]\+$//' $fff | unexpand -t 2 > $fff.2 ; mv $fff.2 $fff ; done

diff --git a/local-bin/install b/local-bin/install
--- a/local-bin/install
+++ b/local-bin/install
@@ -13,7 +13,7 @@ do
 		echo "${prog} - already installed "
 	else
 		echo "${prog}- installing"
-		ln -s "${PWD}/${prog}" 	"${localbin}/" || echo "Failed to link"
+		ln -s "${PWD}/${prog}"	"${localbin}/" || echo "Failed to link"
 	fi
 
 done
